version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/welcome.war
    - appspec.yml
    - scripts/**
